# Serving
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pawelgrzybek.com" # the base hostname & protocol for your site

# Outputting
permalink: /:title/

# Theme specific configuration
title: pawelgrzybek.com
description: >
  Hi there, I'm Pawel Grzybek, Front-end Developer from Poland.
  Nowadays I live in Northampton (UK). When I'm not coding,
  I'm spinning funky vinyl records.

# Contact and social media links
twitter_username: pawelgrzybek
github_username: pawelgrzybek

# Handling Reading
exclude: ['node_modules', 'gulpfile.js', 'package.json']

# Outputting
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

plugins: [jekyll-paginate, jekyll-sitemap]

# Pagination
paginate: 10
